version: "3"

vars:
  TARGET: ./cmd/betteralign
  GIT_LAST_TAG:
    sh: git describe --abbrev=0 --tags 2>/dev/null || echo latest
  GIT_HEAD_COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo unknown
  GIT_TAG_COMMIT:
    sh: git rev-parse --short {{.GIT_LAST_TAG}} 2>/dev/null || echo unknown
  GIT_MODIFIED1:
    sh: git diff {{.GIT_HEAD_COMMIT}} {{.GIT_TAG_COMMIT}} --quiet 2>/dev/null || echo .dev
  GIT_MODIFIED2:
    sh: git diff --quiet 2>/dev/null || echo .dirty
  GIT_MODIFIED:
    sh: echo "{{.GIT_MODIFIED1}}{{.GIT_MODIFIED2}}"
  BUILD_DATE:
    sh: date -u '+%Y-%m-%dT%H:%M:%SZ'

env:
  CGO_ENABLED: 0
  NEWPATH: "{{.GOPATH}}/bin:{{.PATH}}"

tasks:
  default:
    cmds:
      - task: update
      - task: build

  update:
    cmds:
      - go get -u
      - go mod tidy

  check:
    cmds:
      - gomajor list

  fmt:
    cmds:
      - gci write .
      - gofumpt -l -w .

  generate:
    cmds:
      - PATH={{.NEWPATH}} rec -import=unicode/utf8 -pkg betteralign -matchstringutf8=reGeneratedBy '^//\s*Code generated by .* DO NOT EDIT\.$$' > match_generated.go

  test:
    cmds:
      - go test

  build:
    deps:
      - update
      - generate
      - fmt
    cmds:
      - go build -trimpath -pgo=auto -ldflags="-s -w -extldflags '-static' -X main.GitTag={{.GIT_LAST_TAG}} -X main.GitCommit={{.GIT_HEAD_COMMIT}} -X main.GitDirty={{.GIT_MODIFIED}} -X main.BuildTime={{.BUILD_DATE}}" -o {{.TARGET}} ./cmd/betteralign

  build-debug:
    deps:
      - update
      - generate
      - fmt
    env:
      CGO_ENABLED: 1
    cmds:
      - go build -ldflags="-X main.GitTag={{.GIT_LAST_TAG}} -X main.GitCommit={{.GIT_HEAD_COMMIT}} -X main.GitDirty={{.GIT_MODIFIED}} -X main.BuildTime={{.BUILD_DATE}}" -race -o {{.TARGET}} ./cmd/betteralign

  lint:
    deps:
      - generate
      - fmt
    cmds:
      - golangci-lint run --timeout 5m

  release:
    cmds:
      - goreleaser release --clean -p 4
